# Generated by Django 5.2.6 on 2026-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='assistant_c_user_id_5a9081_idx',
            old_name='assistant_c_user_id_created_idx',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
